@startuml

class Jugador{
      + Jugador(RenderWindow& ventana)
  + moverDerecha()
  + moverIzquierda()
  + dibujar(RenderWindow& ventana)
  + escalarPaleta()
  + restaurarEscala()
  + getPosition() : FloatRect
  - paleta : RectangleShape
}

class Puntuaje {
  - puntuacion: int
  - textoPuntuacion: sf::Text
  - fuente: sf::Font
  + Puntuaje()
  + incrementarPuntuacion(puntos: int)
  + reiniciarPuntuacion()
  + draw(window: RenderWindow&)
}